### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by ivnvrmn** [ivnvrmn/CryptoMoon#1]
![photo_2017-09-22_09-26-12](https://user-images.githubusercontent.com/24662633/30724329-243791b2-9f78-11e7-8f03-20c553ce8b57.jpg)
![photo_2017-09-22_09-27-31](https://user-images.githubusercontent.com/24662633/30724346-46a94f4c-9f78-11e7-9225-9037ad4e89d6.jpg)
![photo_2017-09-22_09-27-26](https://user-images.githubusercontent.com/24662633/30724348-4904915c-9f78-11e7-9886-0cf7904d0b6e.jpg)

**Comment by ebabel** [comment]
fyi you can host these in an 'artwork' folder in the repo and then reference markdown like so:
`![alt text](artwork/screen1.png?raw=true)`
