### ISSUE TITLE
cannot delete coin added to the holdings list

### ISSUE THREAD

**Issue by AKprisonER** [ivnvrmn/CryptoMoon#13]
_AM i the only one who doesn't see that option to delete a coin from the list_

**Comment by AKprisonER** [comment]
At first launch, the app didn't show "sort by"
" Delete "
" Coin holdings "
After a coule of restart and reset, apps works as like.
Device : Mi note4, Redmi 4a, Samsung s6

**Comment by ivnvrmn** [comment]
@AKprisonER You can delete coin from holdings by swiping it to the right. 
In the main coins fragment, you can delete it by long tap. 

"Coin holdings" appears only when added at least one transaction.

**Comment by AKprisonER** [comment]
That works. But i am talking about app side code.. I found that fragment initialization didn't work when i compiled. Anyway wll sort it out..
Thanks
